image: python:latest

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  GIT_SUBMODULE_STRATEGY: recursive
  GIT_SUBMODULE_DEPTH: 1

cache:
  paths:
    - .cache/pip

before_script:
  - apt update ; apt upgrade -y;
  - apt install -y cmake doxygen graphviz python3 python3-pip ninja-build libnuma-dev ccache
  - python --version ; pip --version
  - pip install virtualenv
  - virtualenv venv
  - source venv/bin/activate
  - pip install conan gcovr meson pyelftools
  - conan profile detect --force

stages:
  - setup
  - build
  - deploy

setup:
  stage: setup
  script:
    - chmod +x ./build.sh
    - ./build.sh -s

build:Debug:
  stage: build
  script:
    - ./build.sh -c Debug -a

build:Release:
  stage: build
  script:
    - ./build.sh -c Release -a

deploy:
  stage: deploy
  script: echo "deploy success"
  environment: production

